-- Famous Foods lead table
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;

-- Public website needs INSERT only.
create policy "Allow public lead inserts"
on public.leads
for insert
to anon
with check (
  char_length(trim(name)) between 1 and 100
  and phone ~ '^[6-9][0-9]{9}$'
);

-- Do NOT create a public SELECT policy.
-- View/export leads from the Supabase dashboard using an authenticated admin account.
