-- Famous Foods lead table
create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  created_at timestamptz not null default now()
);

alter table public.leads enable row level security;

-- Public website needs INSERT only.
-- drop-if-exists keeps this whole file safe to re-run any time.
drop policy if exists "Allow public lead inserts" on public.leads;
create policy "Allow public lead inserts"
on public.leads
for insert
to anon
with check (
  char_length(trim(name)) between 1 and 100
  and phone ~ '^[6-9][0-9]{9}$'
);

-- Do NOT create a public (anon) SELECT policy — visitor leads stay private.
-- Admins sign in via Supabase Auth and read them on admin.html (policy below).

-- ===== Admin leads viewer (admin.html) =====
-- Allows the signed-in admin account to read leads on the admin.html page.
-- Create your admin login in Supabase: Authentication → Users → Add user
-- (email + a strong password, keep "Auto Confirm User" enabled).
-- This section is safe to run on its own if you already ran the schema above.
drop policy if exists "Admins can view leads" on public.leads;
create policy "Admins can view leads"
on public.leads
for select
to authenticated
using (true);

-- ===== Returning-visitor gate login =====
-- Lets the website gate recognise a known customer by phone number alone on
-- repeat visits (name is never asked again). index.html calls lead_login(phone)
-- and only asks for the name when the number is not in the database.
-- Safe to re-run.

-- 1. Keep one record per customer (removes duplicates from repeat visits,
--    keeps the earliest record).
delete from public.leads a
using public.leads b
where a.phone = b.phone
  and a.id > b.id;

-- 2. Enforce one record per number going forward (website inserts use
--    "ignore duplicates", so repeat registrations never create junk rows).
create unique index if not exists leads_phone_uniq on public.leads(phone);

-- 3. Phone-only login check for the gate (returns the stored name, or null).
--    Reveals nothing else — only works one number at a time.
create or replace function public.lead_login(p_phone text)
returns text
language sql
security definer
set search_path = public
as $$
  select name from public.leads where phone = p_phone limit 1;
$$;

grant execute on function public.lead_login(text) to anon;
